spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
  jpa:
    generate-ddl: true
    hibernate:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true

openapi:
  service-key: ${OPENAPI_SERVICE_KEY}
  weather-base-url: http://apis.data.go.kr/1360000/MidFcstInfoService

