spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DATABASE_NAME}?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true

openapi:
  service-key: ${OPENAPI_SERVICE_KEY}
  weather-base-url: http://apis.data.go.kr/1360000/MidFcstInfoService

